### ISSUE TITLE
Porting to STM32F4 

### ISSUE THREAD

**Issue by Simon-L** [omriiluz/WS2812B-LED-Driver-ChibiOS#1]
I am relatively new to ChibiOS.
I have a STM32F4-Discovery and I'd like to port the NeoPixel driver you wrote to it.
I've managed to compile it with minimal modifications, only the LED names used in the thread in the main.c file.

In the comments you mention it assumes a 72MHz CPU frequency, what should I change to make it work for 168MHz ? I tried modifying the clock and period of pwmc2 and pwmc3 but from what I understand the values shouldn't be different for STM32F4 because they are chosen to work with the specification. It is unclear to me what in the code makes the PWM affected by the CPU frequency specifically when defining PWMConfig.

I tried with the same settings and the resulting signal is very weak and full of noise, it doesn't really look like PWM...
What wiring did you use to connect the led strip ? did you use the onboard 5V as power supply ?

Great project &
Thanks in advance !

**Comment by omriiluz** [comment]
Hi Simon,
I have an STM32F4-Discovery board here, so if you can create a branch with your modification I can test it locally and tell you what's going on.

In terms of wiring - for the end project I used 100ft of cat5 cable, using 2 pairs for 2 strips, each 900 leds in length. A cable that long did cause some ringing of the signal, but it was clean enough for the WS2812 to extract the signal.

in terms of power - you can use the onboard 5v supply to drive a few leds, but not more than that. I used the 5v rails of a beefy ATX power supply to drive 1800 leds.

Thanks,
Omri

**Comment by Simon-L** [comment]
Hi !
I created a fork of your repo to work on it:
https://github.com/Simon-L/WS2812B-LED-Driver-ChibiOS

I took mcuconf.h and other files from the F4 demo and changed the lines in the makefile to compile for F4.
I changed the main.c led init line to reflect my settings, I have a 30 leds strip.
Can you confirm it's using pin 1 of GPIOA ? That's what your comment says but the mask used in your example is 0b00000010, that is 2 and given my skills it is unclear to me from looking at the code how to check that properly.

I modified the numbers used for clock and period of pwmc2 and pwmc3 in LEDDriver.c but it shouldn't change anything since the result is the same... Maybe I'm wrong ?
It still does not work, doesn't even light up dimly or erratically, nothing !

Right now I am looking at the pin definition and mode setting for PWM.
From what I understood should use an "alternate" mode but I don't see it being configured as such in LEDDriver.c.
Can you explain what is being set on line 49 ?
`palSetGroupMode(port, sMask, 0, PAL_MODE_OUTPUT_PUSHPULL|PAL_STM32_OSPEED_HIGHEST|PAL_STM32_PUDR_FLOATING);`

I am new to ChibiOS and having a amazingly hard time figuring out how things work.
Thanks for your time !

**Comment by omriiluz** [comment]
A quick update - I've been working on your port but it's proving harder than anticipated, the DMA trigger mapping is different than in the STM32F373. Give me a few more days to try and solve it.

**Comment by omriiluz** [comment]
I created a branch of the project which ports to the STM32F4-DISCOVERY board (https://github.com/omriiluz/WS2812B-LED-Driver-ChibiOS/tree/STM32F4-DISCOVERY-PORT). This branch is based on your fork plus changes I've added which are documented. I also created a pull request to sync the changes back to your fork.
