### ISSUE TITLE
Might be possible with fewer timers and DMA streams

### ISSUE THREAD

**Issue by trepidacious** [omriiluz/WS2812B-LED-Driver-ChibiOS#3]
I ran into a project  that uses a similar technique, but using DMA to send new pulse width values to the timer as it runs, which means it only needs one timer, and one DMA stream to set the pulse width on each cycle. I was wondering if you had considered a similar approach?

http://eliaselectronics.com/driving-a-ws2812-rgb-led-with-an-stm32/
https://github.com/devthrash/STM32F1-workarea/tree/master/Project/WS2812

**Comment by omriiluz** [comment]
The other project still need the microcontroller to do timing critical "work" to output the right bit stream. My library creates a completely independent output logic. Once the timers and DMA channels are setup and running, the frame buffer is being translated and output continuously without any microcontroller intervention. This allows a much simpler application logic and frees up CPU time to do other work. This is the way hardware frame buffers have been working for many years. It has a more complex configuration and uses more timers and DMA channels, but if these are available on your microcontroller your application logic will be simpler. if you don't have these available, you can use the other solution.
